# Generated by Django 4.1.6 on 2023-05-15 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_shippingaddress_is_default_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True),
        ),
    ]
