# Generated by Django 4.1.6 on 2023-06-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
