# Generated by Django 4.1.6 on 2023-04-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_description', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(blank=True, max_length=100, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('filter_name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Filter',
            },
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('filteroption_id', models.AutoField(primary_key=True, serialize=False)),
                ('filteroption_name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('filter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.filter')),
            ],
            options={
                'db_table': 'FilterOption',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword_name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Keyword',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('main_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_category_name', models.CharField(max_length=100)),
                ('main_category_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('main_category_description', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincategories', to='products.brand')),
            ],
            options={
                'db_table': 'MainCategory',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('subcategory_description', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('product_countStock', models.IntegerField(blank=True, default=0, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('filteroption_id', models.ManyToManyField(blank=True, related_name='products', to='products.filteroption')),
                ('keyword_id', models.ManyToManyField(blank=True, to='products.keyword')),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.maincategory')),
                ('subcategory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subcategory')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.AddField(
            model_name='filter',
            name='main_category_id',
            field=models.ManyToManyField(related_name='filters', to='products.maincategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='main_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.maincategory'),
        ),
    ]
