# Generated by Django 4.1.6 on 2023-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
