# Generated by Django 4.1.6 on 2023-04-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteroption',
            name='filteroption_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
