# Generated by Django 4.1.6 on 2023-04-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_maincategory_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='main_category_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
