# Generated by Django 4.1.6 on 2023-05-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_category_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'Slider',
            },
        ),
    ]
