# Generated by Django 4.1.6 on 2023-05-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cart_total_price_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
