# Generated by Django 4.1.6 on 2023-05-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
