# Generated by Django 4.1.6 on 2023-05-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_cartitem_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session_id',
        ),
    ]
