# Generated by Django 4.1.6 on 2023-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_cartitem_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='session_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
