# Generated by Django 4.1.6 on 2023-05-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_wishlist_session_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
