# Generated by Django 4.1.6 on 2023-05-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_review_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
