# Generated by Django 4.1.6 on 2023-06-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='main_category_description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_description',
        ),
    ]
