# Generated by Django 4.1.6 on 2023-06-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_relatedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedProduct',
        ),
    ]
