# Generated by Django 4.1.6 on 2023-06-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_delete_relatedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
