# Generated by Django 4.1.6 on 2023-06-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
