# Generated by Django 4.1.6 on 2023-06-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Refused')], default='P', max_length=15, null=True),
        ),
    ]
